# app/services/dashboard_engine.py
"""
MODULE 2 — ENTERPRISE DASHBOARD ENGINE
Creates dashboard layouts, widget configs, and theme management.
Consumes chart_data already generated by analysis_service.py.
"""

import uuid
import json
from typing import Optional


WIDGET_TYPES = ["kpi", "gauge", "radar", "line", "bar", "pie",
                "stacked_bar", "area", "scatter", "histogram",
                "progress", "metric_card", "ranking_table", "heatmap"]

DEFAULT_THEMES = {
    "dark_blue": {
        "bg":       "rgb(8,12,22)",
        "surface":  "rgba(255,255,255,0.04)",
        "border":   "rgba(255,255,255,0.08)",
        "accent":   "rgba(99,179,237,0.9)",
        "text":     "rgba(255,255,255,0.88)",
        "muted":    "rgba(255,255,255,0.4)",
        "palette":  ["#63b3ed","#68d391","#f6ad55","#fc8181","#b794f4","#81e6d9"],
    },
    "neon_dark": {
        "bg":       "rgb(5,5,15)",
        "surface":  "rgba(255,255,255,0.03)",
        "border":   "rgba(130,255,200,0.12)",
        "accent":   "rgba(0,255,180,0.85)",
        "text":     "rgba(255,255,255,0.92)",
        "muted":    "rgba(255,255,255,0.35)",
        "palette":  ["#00ffb4","#00d4ff","#ff6b6b","#ffd93d","#c77dff","#4cc9f0"],
    },
    "corporate": {
        "bg":       "rgb(15,20,35)",
        "surface":  "rgba(255,255,255,0.05)",
        "border":   "rgba(255,255,255,0.09)",
        "accent":   "rgba(79,140,255,0.9)",
        "text":     "rgba(255,255,255,0.9)",
        "muted":    "rgba(255,255,255,0.45)",
        "palette":  ["#4f8cff","#43e97b","#fa8231","#e74c3c","#a29bfe","#00cec9"],
    },
}


def create_widget(widget_type: str, metric: str, chart_data: dict,
                  position: dict = None, size: dict = None) -> dict:
    """
    Create a single dashboard widget config.
    Binds widget to real data from chart_data.
    """
    wid = str(uuid.uuid4())[:8]

    # Extract real data for this widget
    bound_data = _bind_widget_data(widget_type, metric, chart_data)

    return {
        "id":        wid,
        "type":      widget_type,
        "metric":    metric,
        "title":     _widget_title(widget_type, metric),
        "position":  position or {"x": 0, "y": 0, "w": 2, "h": 2},
        "size":      size or {"w": 2, "h": 2},
        "data":      bound_data,
        "config":    _widget_config(widget_type, metric, chart_data),
    }


def _widget_title(widget_type: str, metric: str) -> str:
    titles = {
        "kpi":           f"Total {metric}",
        "gauge":         f"{metric} Gauge",
        "radar":         f"Performance Radar",
        "line":          f"{metric} Trend",
        "bar":           f"{metric} by Category",
        "pie":           f"{metric} Distribution",
        "stacked_bar":   f"Stacked {metric}",
        "area":          f"{metric} Area Trend",
        "progress":      f"{metric} Progress",
        "metric_card":   f"{metric} Overview",
        "ranking_table": f"Top {metric} Rankings",
        "heatmap":       f"{metric} Heatmap",
    }
    return titles.get(widget_type, metric)


def _widget_config(widget_type: str, metric: str, chart_data: dict) -> dict:
    """Extra config options per widget type."""
    if widget_type == "gauge":
        # Find min/max for gauge range
        measures = chart_data.get("__measures__", {})
        m_data   = measures.get(metric, {})
        return {
            "min":    m_data.get("min", 0),
            "max":    m_data.get("max", 100),
            "target": m_data.get("avg", 50),
            "thresholds": [
                {"value": 33, "color": "#fc8181"},
                {"value": 66, "color": "#f6ad55"},
                {"value": 100,"color": "#68d391"},
            ],
        }
    if widget_type == "kpi":
        measures = chart_data.get("__measures__", {})
        m_data   = measures.get(metric, {})
        return {
            "value":      m_data.get("sum", m_data.get("avg", 0)),
            "change_pct": m_data.get("growth_rate_pct", 0),
            "format":     m_data.get("format", "number"),
        }
    if widget_type == "progress":
        measures = chart_data.get("__measures__", {})
        m_data   = measures.get(metric, {})
        val = m_data.get("agg", {}).get("sum", 0) or 0
        mx  = m_data.get("agg", {}).get("max", 100) or 100
        return {"value": val, "max": mx, "pct": round(val/mx*100, 1) if mx else 0}
    return {}


def _bind_widget_data(widget_type: str, metric: str, chart_data: dict) -> list | dict:
    """Bind widget to real chart_data entries."""
    if widget_type in ("line", "area"):
        datasets = chart_data.get("line", [])
        match = next((d for d in datasets if metric.lower() in d.get("id","").lower()), None)
        return match["data"] if match else (datasets[0]["data"] if datasets else [])

    if widget_type in ("bar", "stacked_bar", "ranking_table"):
        datasets = chart_data.get("bar", [])
        match = next((d for d in datasets if metric.lower() in d.get("id","").lower()), None)
        return match["data"] if match else (datasets[0]["data"] if datasets else [])

    if widget_type == "pie":
        datasets = chart_data.get("pie", [])
        match = next((d for d in datasets if metric.lower() in d.get("id","").lower()), None)
        return match["data"] if match else (datasets[0]["data"] if datasets else [])

    if widget_type == "scatter":
        datasets = chart_data.get("scatter", [])
        return datasets[0]["data"] if datasets else []

    if widget_type == "histogram":
        datasets = chart_data.get("histogram", [])
        match = next((d for d in datasets if metric.lower() in d.get("id","").lower()), None)
        return match["data"] if match else (datasets[0]["data"] if datasets else [])

    if widget_type == "radar":
        # Build radar from measures
        measures = chart_data.get("__measures__", {})
        radar_data = []
        for col, m in list(measures.items())[:7]:
            agg = m.get("agg", {})
            mx  = agg.get("max", 1) or 1
            avg = agg.get("avg", 0) or 0
            radar_data.append({"metric": col[:12], "value": round(avg / mx * 100, 1)})
        return radar_data

    if widget_type in ("kpi", "metric_card", "gauge", "progress"):
        measures = chart_data.get("__measures__", {})
        m_data   = measures.get(metric, {})
        return m_data.get("agg", {})

    return []


def build_dashboard_layout(chart_data: dict, semantic_model: dict,
                           layout_type: str = "executive") -> dict:
    """
    Auto-generate a full dashboard layout from chart_data + semantic_model.
    layout_type: 'executive' | 'operational' | 'financial' | 'sales'
    """
    kpi_candidates = semantic_model.get("kpi_candidates", [])
    measures       = semantic_model.get("measures", [])

    # Attach measures to chart_data for widget binding
    chart_data["__measures__"] = {
        m["name"]: {**m, **m.get("agg", {})}
        for m in measures
    }

    widgets = []
    grid_x, grid_y = 0, 0

    # Row 1: KPI cards (top 4)
    for i, kpi in enumerate(kpi_candidates[:4]):
        widgets.append(create_widget(
            "kpi", kpi["name"], chart_data,
            position={"x": i*3, "y": 0, "w": 3, "h": 2},
        ))

    # Row 2: Main trend chart + pie distribution
    all_measures = [m["name"] for m in measures]
    if all_measures:
        widgets.append(create_widget(
            "line", all_measures[0], chart_data,
            position={"x": 0, "y": 2, "w": 8, "h": 4},
        ))
        widgets.append(create_widget(
            "pie", all_measures[0], chart_data,
            position={"x": 8, "y": 2, "w": 4, "h": 4},
        ))

    # Row 3: Bar chart + gauge + radar
    if len(all_measures) >= 2:
        widgets.append(create_widget(
            "bar", all_measures[1], chart_data,
            position={"x": 0, "y": 6, "w": 6, "h": 4},
        ))
        widgets.append(create_widget(
            "gauge", all_measures[0], chart_data,
            position={"x": 6, "y": 6, "w": 3, "h": 4},
        ))
        widgets.append(create_widget(
            "radar", all_measures[0], chart_data,
            position={"x": 9, "y": 6, "w": 3, "h": 4},
        ))

    # Row 4: Ranking table + area chart
    if len(all_measures) >= 3:
        widgets.append(create_widget(
            "ranking_table", all_measures[0], chart_data,
            position={"x": 0, "y": 10, "w": 5, "h": 4},
        ))
        widgets.append(create_widget(
            "area", all_measures[2], chart_data,
            position={"x": 5, "y": 10, "w": 7, "h": 4},
        ))

    return {
        "id":          str(uuid.uuid4())[:8],
        "title":       _dashboard_title(layout_type),
        "layout_type": layout_type,
        "theme":       "neon_dark",
        "grid_cols":   12,
        "grid_rows":   14,
        "widgets":     widgets,
        "created_at":  _now(),
    }


def _dashboard_title(layout_type: str) -> str:
    titles = {
        "executive":   "Executive Dashboard",
        "operational": "Operations Dashboard",
        "financial":   "Financial Dashboard",
        "sales":       "Sales Performance Dashboard",
    }
    return titles.get(layout_type, "Analytics Dashboard")


def _now():
    from datetime import datetime
    return datetime.utcnow().isoformat()


def get_themes() -> dict:
    return DEFAULT_THEMES


def save_dashboard(dashboard: dict) -> str:
    """Serialize dashboard to JSON string (for session storage)."""
    return json.dumps(dashboard)


def load_dashboard(data: str) -> dict:
    """Deserialize dashboard from JSON string."""
    return json.loads(data)